### ISSUE TITLE
Suggested topics for 2023-09-21 meeting

### ISSUE THREAD

**Issue by tobyhodges** [swcarpentry/curriculum-advisors#11]
1. Development of a Curriculum Onboarding presentation for Software Carpentry
    - Summary: The Carpentries is developing curriculum-specific onboarding materials for Instructors for all official curricula, as a deliverable for a grant from The Gordon and Betty Moore Foundation. The Curriculum Team is looking for volunteers from the Curriculum Advisory Committee to help us prepare the onboarding for the Software Carpentry curriculum. In the meeting, I will describe what we hope to achieve in more detail, present the template materials that have been developed for this project, and talk about how Curriculum Advisors could get involved in drafting, reviewing, and/or presenting the onboarding content.
    - Estimated time required to discuss this item: 15 minutes
2. Guiding Learners on how to configure multi-factor authentication on their GitHub accounts
    - Summary: GitHub has begun to require multi-factor authentication (2FA) for all accounts, and the Software Carpentry Git lessons (English & Spanish) need to be updated accordingly. The Curriculum Team has coordinated with Maintainers of these lessons and the Library Carpentry Git lesson, to determine what recommendation we should make to Learners about choosing a 2FA method within these lessons. In the meeting, I will present this and ask the CAC for feedback with the hope that we can proceed with updating the lessons accordingly (I will be making the same presentation to the Library Carpentry CAC as well).
    - Estimated time required to discuss this item: 10 minutes

@Gina123-P if you would prefer to discuss these two items by email, and avoid a CAC meeting this quarter, please let me know and I can send the relevant info to the TopicBox list.

**Comment by Gina123-P** [comment]
@tobyhodges, yh we could have email correspondence for this.

**Comment by Gina123-P** [comment]
But let's open this up to the CAC and let see what they think. 
I will send it to them now.

**Comment by annajiat** [comment]
I am fine with both having a meeting and discussing over email/GitHub issue/topic box.
I will go with whatever you choose.

**Comment by tobyhodges** [comment]
I am going to share details as messages to the CAC TopicBox group, to prevent the need for everyone to attend a meeting. I'll close this issue now.

**Comment by Gina123-P** [comment]
Thank you, Toby!
