### ISSUE TITLE
[git-novice] Replacing the default lesson ("Planets") with an alternative story

### ISSUE THREAD

**Issue by bsmith89** [swcarpentry/curriculum-advisors#5]
Several alternatives to the standard Git lesson have been discussed, mostly intended to replace the "Planets"/"Wolfman" story with a recipe (e.g. Guacamole or Stone Soup). Several of these have been developed into formal lessons using the Carpentries template.

One example of the Guacamole motivation can be found here: http://github-pages.ucl.ac.uk/git-novice/aio/index.html

- [x] Link other alternative lessons

The CAC is empowered to recommend replacing the default git-novice lesson with one of these, if we think it is appropriate.

- [x] Link past discussions.

**Comment by annajiat** [comment]
May be related

- [Should we change the story behind the lesson?](https://github.com/swcarpentry/git-novice/issues/277)
- [Replace Dracula example-project with more realistic project](https://github.com/swcarpentry/git-novice/issues/896)
- [Git lesson from CodeRefinery](https://coderefinery.github.io/git-intro/basics/)
- [replace self-describing edits with representative ones [fix #727]](https://github.com/swcarpentry/git-novice/pull/829)
- [Suggestion for embedding Episode 6 in storyline](https://github.com/swcarpentry/git-novice/issues/773)

**Comment by coatless** [comment]
So, I'm greatly in favor of replacing the `Planets` story line. This seems to be a sore spot in the software carpentry curriculum. 

From our last meeting, we did discuss moving over to a different analogy. It seems like some instructors have opted to move toward a cooking analogy. Alternatively, we could re-phrase the lesson from the viewpoint of a photographer taking photos of the source code.

I suppose the question here is how do we enact this change? Are we allowed to authorize and, then, begin implementation? Or do we need to engage with the community maintainers and alternative lesson developers to generate a meaningful change?

**Comment by bsmith89** [comment]
Thanks for your input, James!

> I suppose the question here is how do we enact this change? Are we allowed to authorize and, then, begin implementation? Or do we need to engage with the community maintainers and alternative lesson developers to generate a meaningful change?

Yes, I share this uncertainty. I would love to get guidance on this from @ErinBecker and @tobyhodges, as—to my knowledge—they have the most concrete vision for our purview here.

However, I _also_ think that we have a role in deciding how to proceed here and we can propose a course of action that seems appropriate to us. In the next comment I'll propose one possibility...

**Comment by bsmith89** [comment]
One possibility (that I'll summarize here) is that, as a CAC:

1. We draft, ratify by a committee vote, and publicize an explicit opinion of the SWC CAC that the Planets Story should be replaced with a Stone Soup Recipe
2. We select and highlight existing lesson materials to be used as a model for this alternative story
3. We, along with Carpentries leadership and staff, recruit a current or new maintainer to spearhead the process
4. This maintainer will fork the existing lesson and oversee story substitutions
5. Carpentries staff will publicize the need and recruit community members to implement these changes, perhaps during a Carpentries Hackathon event
6. We proactively encourage this development effort, perhaps setting a desired timeline for implementation
7. Once the maintainer is satisfied with the forked lesson we draft and ratify a follow-up opinion that it is the new "official curriculum lesson" and that e.g. the link on the website should be swapped over.

Clearly this process will require buy-in and effort from quite a few people, including the current Git Lesson maintainers who we would not want to alienate in the process and who would presumably still be maintainers after the switch. I would also like to see more direct support from Carpentries staff, perhaps including a staff member leading the implementation process.

I'm suggesting the above approach primarily for discussion purposes. I would love to see alternative proposals as well (for instance asking the current maintainers to make all of these changes themselves). I am, personally, not in favor of _our_ committee being officially responsible for making changes directly, although I can imagine our members contributing individually.

**Comment by tobyhodges** [comment]
Thanks for leading this conversation, @bsmith89. Speaking from a Curriculum Team perspective, this kind of community-driven approach is exactly what we would hope to see and certainly you can count on our support. We are hoping to soon bring in a part-time team member in a _Contributor Experience Lead_ role that would be a very good fit to facilitate large-scale curriculum updates like this and I would also be keen to get involved.

I do not believe it is reasonable to expect the current lesson Maintainers to take on such a major update to the lesson - certainly it is outside [the scope of the role they agreed to take on](https://docs.carpentries.org/topic_folders/maintainers/maintainers.html). The same, of course, is true of [you all as Curriculum Advisors](https://docs.carpentries.org/topic_folders/lesson_development/curriculum_advisory_committees.html#other-members). In my opinion however, even though the execution of the project may be led by others in the community, some active engagement from Maintainers and the CAC throughout the process will be vital to its success.

**Comment by bsmith89** [comment]
Great! Thanks for the input, Toby.

When might a Contributor Experience Lead be available to take on a project like this?

Perhaps we can get this near the front of their queue if we act with some urgency.

**Comment by tobyhodges** [comment]
The timeline is unclear, unfortunately, but I hope they will join in the next couple of months. 

That said, I think it would also be helpful to wait until the Workbench rollout is complete (start of May) before work starts on major updates to the lesson content. That doesn't mean you/we can't get started on the first three steps you described above though.

**Comment by kekoziar** [comment]
Just an observation: many of the questions/comments advocating to remove the "movie monsters" story have been because it's a Eurocentric storyline and considered "childish," but replacing it with "Stone Soup" just replaces it with a different European folktale (child's story).

**Comment by bsmith89** [comment]
@tracykteal, for one, suggested that it may cross-cultural in [this comment from 2018](https://github.com/swcarpentry/git-novice/issues/277#issuecomment-365289641).

The strongest reasons to push for a change would be if its distracting/confusing/additional cognitive overhead for learners. My own impression is that this is the case, and there _seems_ to be widespread interest among instructors to change it, but admittedly, I don't think that data has been formally collected.

For me, Stone Soup has much less to do with it being a story, and is instead focused on using the text of an evolving recipe to demonstrate Git fundamentals. Instructors would be free (and encouraged?) to choose any recipe they want (e.g. guacamole), but with Stone Soup as a "generic" option presented in the prepared lesson.

**Comment by annajiat** [comment]
Until we find a better one, I would like to vote for the stone soup story being cross-cultural, as we read that in childhood.

In general, I have seen other communities using cooking recipes as an example not just for git lessons, but for other tutorials as well.

**Comment by martinosorb** [comment]
This has now been completed, and this issue can be closed.
